# Generated by Django 2.1.12 on 2019-10-02 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewflow', '0006_i18n'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Assigned'),
        ),
    ]
