# Generated by Django 2.2.6 on 2019-10-28 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewflow', '0008_jsonfield_and_artifact'),
        ('viewflow', '0008_merge'),
    ]

    operations = [
    ]
