# Generated by Django 4.1.9 on 2023-07-05 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("viewflow", "0010_viewflow20"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="created",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, verbose_name="Created"
            ),
        ),
        migrations.AddIndex(
            model_name="process",
            index=models.Index(
                fields=["artifact_content_type", "artifact_object_id"],
                name="viewflow_pr_artifac_64c8a3_idx",
            ),
        ),
    ]
