# Generated by Django 4.1.9 on 2023-09-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("viewflow", "0011_alter_task_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="process",
            name="data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="task",
            name="data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
