# Generated by Django 6.1b1 on 2026-07-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewflow", "0014_alter_process_parent_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="scheduled",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="Scheduled"
            ),
        ),
    ]
